### ISSUE TITLE
Output all files per chunk

### ISSUE THREAD

**Issue by krisztianb** [wayou/print-chunks-plugin#1]
Hello!

Thanks for publishing this plugin on NPM. There is one thing I noticed while using it. Currently the output of the plugin is limited to a certain amount of files per chunk.

**Example output:**

```js
{
    id: 'index',
    name: 'index',
    modules: [
      4,
      './app/index.js',
      './node_modules/@babel/polyfill/lib/index.js',
      './node_modules/@babel/polyfill/lib/noConflict.js',
      './node_modules/ansi-html/index.js',
      './node_modules/ansi-regex/index.js',
      './node_modules/core-js/es6/index.js',
      './node_modules/core-js/fn/array/flat-map.js',
      './node_modules/core-js/modules/_math-log1p.js',
      './node_modules/core-js/modules/_math-sign.js',
      './node_modules/core-js/modules/_meta.js',
      './node_modules/core-js/modules/_microtask.js',
      './node_modules/core-js/modules/_new-promise-capability.js',
      ... 241 more items
    ]
  }
]
```

Would you care to update the code to show all files as suggested [here](https://stackoverflow.com/questions/29966345/how-to-get-a-list-of-all-files-or-modules-included-per-chunk-in-webpack/57279355#57279355)?

**Comment by wayou** [comment]
fixed with new option added.
try it out and let me know if there's another problem.

**Comment by krisztianb** [comment]
That was quick. Thank you. I'll test it soon.
